### ISSUE TITLE
Browsers are not closed after tests execution

### ISSUE THREAD

**Issue by guilhotarras** [Andras-Marozsi/cucumber-parallelly#5]
After running the tests, the browsers are not closed.

**Comment by andras-marozsi** [comment]
Yeah, you have to explicitly close them. Like:
```
this.After(function () {
  return this.browser.quit()
})
```
Gives you quite a lot freedom in the tests. E.g.: you can add a check for an environment variable and choose not to close the browser if there was a failure and you are in "debug" mode. Sometimes much more helpful than just a screenshot. You can have this state enabled locally and disabled when running the tests as part of CI.

Just make sure you close the browser AFTER you took a screenshot, etc, otherwise you can run into intermittent failures in the after hook(s).
